name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Versions
        run: |
          docker --version
          docker-compose version
      - name: Pull Cached Container
        run: docker pull "nrel/api-umbrella-dev-env:${GITHUB_REF#refs/heads/}" || true
      - name: Build Container
        run: docker-compose build --pull
      - name: Docker Registry Login
        run: docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Container
        run: docker push "nrel/api-umbrella-dev-env:${GITHUB_REF#refs/heads/}"
      - name: Lint
        run: docker-compose run --rm app make lint
      - name: Test
        run: docker-compose run --rm -e N=12 app make test
